// flow-typed signature: 28123e08e1277102f80a94a8db5eb7d0
// flow-typed version: <<STUB>>/indefinite-article_v0.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'indefinite-article'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'indefinite-article' {
  declare module.exports: (word: string) => string;
}
